In [4]:
import numpy as np

- 0D Tensor or Scalar

In [5]:
# creating 0D tensor / array / scalar
a = np.array(4)
a

array(4)

In [6]:
a.ndim

0

---

- 1D-Tensor or Vector

In [7]:
# creating 1D tensor / array / vector
b = np.array((1,2,3,4))

In [8]:
b

array([1, 2, 3, 4])

In [9]:
b.ndim

1

---

- 2D-Tensor or Matrix

In [10]:
# creating 2D tensor / Matrix
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
mat.shape

(3, 3)

In [11]:
mat.ndim

2

---

- 3D-Tensor

In [14]:
# creating 3d tensor
tensor_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

tensor_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [15]:
tensor_3d.ndim

3

In [17]:
tensor_3d.shape

(2, 3, 4)

---

- 4D-tensor

In [21]:
tensor_4d = np.array(
    [
        [
            [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]],

            [[13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]],

        ],

        [
            [[25, 26, 27, 28],
             [29, 30, 31, 32],
             [33, 34, 35, 36]],

            [[37, 38, 39, 40],
             [41, 42, 43, 44],
             [48, 46, 47, 48]]
        ]
    ]
)

tensor_4d

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],

        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [48, 46, 47, 48]]]])

In [22]:
tensor_4d.shape

(2, 2, 3, 4)

In [23]:
tensor_4d.ndim

4

---

- 5D-Tensor

In [29]:
tensor_5d = np.array(
    [
        [
        [
            [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]],

            [[13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]],

        ],

        [
            [[25, 26, 27, 28],
             [29, 30, 31, 32],
             [33, 34, 35, 36]],

            [[37, 38, 39, 40],
             [41, 42, 43, 44],
             [48, 46, 47, 48]]
        ]
    ],

        [
        [
            [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]],

            [[13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]],

        ],

        [
            [[25, 26, 27, 28],
             [29, 30, 31, 32],
             [33, 34, 35, 36]],

            [[37, 38, 39, 40],
             [41, 42, 43, 44],
             [48, 46, 47, 48]]
        ]
    ]

        ]
)

tensor_5d

array([[[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[25, 26, 27, 28],
          [29, 30, 31, 32],
          [33, 34, 35, 36]],

         [[37, 38, 39, 40],
          [41, 42, 43, 44],
          [48, 46, 47, 48]]]],



       [[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[25, 26, 27, 28],
          [29, 30, 31, 32],
          [33, 34, 35, 36]],

         [[37, 38, 39, 40],
          [41, 42, 43, 44],
          [48, 46, 47, 48]]]]])

In [30]:
tensor_5d.shape

(2, 2, 2, 3, 4)

In [27]:
tensor_5d.ndim

5

---